SUPABASE_URL = 'https://dimomudratvmsrktlzve.supabase.co'

SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbW9tdWRyYXR2bXNya3RsenZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODgzMDIsImV4cCI6MjA1NDI2NDMwMn0.BAZDg2Lq_EUaXlkOBNK9phn108_sD5R5VDMwPEHfWXI'

headers = {
        'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbW9tdWRyYXR2bXNya3RsenZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODgzMDIsImV4cCI6MjA1NDI2NDMwMn0.BAZDg2Lq_EUaXlkOBNK9phn108_sD5R5VDMwPEHfWXI',
        'Authorization': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbW9tdWRyYXR2bXNya3RsenZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODgzMDIsImV4cCI6MjA1NDI2NDMwMn0.BAZDg2Lq_EUaXlkOBNK9phn108_sD5R5VDMwPEHfWXI',
        'Content-Type' : 'application/json'
    }